# Reject rules
host-keyword,adserv,reject
host-keyword,advert,reject
host-keyword,adsdk,reject
host-keyword,adx,reject
host-keyword,adtarget,reject
host-keyword,adsys,reject
host-keyword,beacon,reject
host-keyword,tracker,reject
host-keyword,umeng,reject
host-keyword,dsp,reject
host-keyword,rtb,reject
host-keyword,adnet,reject
host-keyword,admob,reject
host-keyword,pangolin,reject
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/dns-filter.txt,set
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt,set
https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Surge.list,set
https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt,set
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/filter/filter.list