# Reject rules
host-keyword,adserv,reject
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt,set
https://raw.githubusercontent.com/geekdada/surge-list/master/domain-set/chinese-filter.txt,set
https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Surge.list,set
https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/domains.txt,set
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/filter/filter.list