# Rewrite rules
(?i)\b/ad/ url reject
(?i)\b/ads/ url reject
(?i)\b/adv/ url reject
(?i)\b/advert/ url reject
(?i)\b/adx/ url reject
(?i)\b/ad\? url reject
(?i)\b/ads\? url reject
(?i)\badvertisement url reject
(?i)\badvertising url reject
(?i)\bsplash_screen url reject
https://raw.githubusercontent.com/fmz200/wool_scripts/main/QuantumultX/rewrite/rewrite.snippet,qx