name: Update Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download and modify gfw.txt
        run: |
          curl -o gfw.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt
          sed -E 's/DOMAIN-SUFFIX,(.+)/host-suffix, \1, proxy/' gfw.txt > GFW.snippet

      - name: Download and modify anti-ad-surge.txt
        run: |
          curl -o anti-ad-surge.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
          sed -E 's/DOMAIN-SUFFIX,(.+)/host-suffix, \1, reject/' anti-ad-surge.txt > antiAD.snippet

      - name: Download and rename Country.mmdb
        run: |
          curl -o GeoIP.mmdb https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add GFW.snippet antiAD.snippet GeoIP.mmdb
          git commit -m "Update Files"
          git push
