name: Update Files

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main

jobs:
  update_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify and rename files
        run: |
          curl -o gfw.txt https://raw.githubusercontent.com/Loyalsoldier/surge-rules/release/ruleset/gfw.txt
          curl -o anti-ad-surge.txt https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-surge.txt
          curl -o GeoIP.mmdb https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country.mmdb

          sed -i 's/DOMAIN-SUFFIX,\(.*\)/host-suffix, \1, proxy/' gfw.txt
          sed -i 's/DOMAIN-SUFFIX,\(.*\)/host-suffix, \1, reject/' anti-ad-surge.txt

          mv gfw.txt GFW.snippet
          mv anti-ad-surge.txt antiAd.snippet

      - name: Verify files generation
        run: ls GFW.snippet antiAd.snippet GeoIP.mmdb

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Update Files"
          git push origin main

      - name: Verify push result
        run: |
          git log -1
          git branch --contains $(git rev-parse HEAD)
          git show-ref --verify --quiet refs/heads/main
 